### ISSUE TITLE
Branching and merging best practices in Git is "Gitflow Workflow"

### ISSUE THREAD

**Issue by marzelwidmer** [openwms/interface21-exam-cockpit#9]
It will be nice if the Git repository support the _GitFlow Workflow_. Master is protected and all feature branches will be merged in the develop branch. So Master branch don't have any `-SNAPSHOT` dependencies. 

https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow
https://bitbucket.org/atlassian/jgit-flow/wiki/Home
https://gist.github.com/lemiorhan/97b4f827c08aed58a9d8

I create already a develop branch on my local machine with the Maven Plugin.  So if `interface21-exam-cockpit` want work with the best practice git workflow _GitFlow Workflow_ I push this branch to remote git repository but some changes are needed I think at the moment is something wrong. 

GitHub configuration must change the default branch on develop and protect the master branch.

**Comment by openwms** [comment]
IMO Gitflow is overkill for this project and makes more sense in product development. What about applying the Feature Branch Flow with a dedicated develop branch. See some thoughts on Gitflow https://www.thoughtworks.com/radar/techniques/gitflow

**Comment by openwms** [comment]
set `develop` to default branch
